Update for eforms
open-contracting-extensions/ocds_bid_extension pull request #49
Opened 2023-03-14 01:57 UTC by duncandewhurst

This PR reflects the changes mentioned in https://github.com/open-contracting/european-union-support/issues/94#issuecomment-1467182874 and https://github.com/open-contracting/european-union-support/issues/94#issuecomment-1467195196.

I added the [Country code extension](https://extensions.open-contracting.org/en/extensions/countryCode/) to `dependencies` because `Bid.countriesOfOrigin` reuses the country codelist from that extension. I'm not sure if that's necessary, it might be sufficient to add it to `testDependencies`.

2023-03-29 11:49 UTC, odscjen requested changes
Just a couple of comments.

I assume the removal of `Statistic` to it's own extension and the associated updates to that object and it's codelists will happen in a separate PR?

2023-03-29 11:49 UTC, odscjen commented on README.md
> +In the European Union, this extension's fields correspond to [eForms BG-7 (Notice Result), BG-320 (Tender) and BG-310 (Contract)](https://docs.ted.europa.eu/eforms/latest/reference/business-terms/).
BG-7 contains 3 BT's all of which are discarded in OCDS and only 1 BT from BG-310 uses this extension

2023-03-29 11:49 UTC, odscjen commented on README.md
> +In the European Union, this extension's fields correspond to [eForms BG-7 (Notice Result), BG-320 (Tender) and BG-310 (Contract)](https://docs.ted.europa.eu/eforms/latest/reference/business-terms/).
```suggestion
In the European Union, this extension's fields correspond to [BG-320 (Tender) and BT-3202 (Contract Tender ID)](https://docs.ted.europa.eu/eforms/latest/reference/business-terms/). See [OCDS for eForms](https://standard.open-contracting.org/profiles/eforms/latest/en/) for the correspondences to eForms fields.
```

2023-03-29 21:58 UTC, duncandewhurst commented
> I assume the removal of Statistic to it's own extension and the associated updates to that object and it's codelists will happen in a separate PR?

Yep, I think we can do a separate PR for that when we come to author the statistics extension.

2023-04-27 01:57 UTC, jpmckinney commented on release-schema.json
> +          "description": "Whether the bid is a variant. A variant is a bid that fulfils the buyer's needs in a different way than that expressed in the procurement documents.",
American spelling. Align with wording in submissionTerms.

```suggestion
          "description": "Whether the bid is a variant. A variant is a bid that fulfills the buyer's needs differently than as proposed in the procurement documents.",
```

2023-04-27 01:57 UTC, jpmckinney commented on release-schema.json
> +          "description": "Whether this bid is ranked. For more information, see `.rank`.",
We generally avoid descriptions that require a separate lookup to understand the semantics. I think we can leave this short (the user can read the adjacent field), or we can have some repetition.

```suggestion
          "description": "Whether this bid is ranked.",
```

2023-04-27 01:57 UTC, jpmckinney commented on README.md
> +
Since this extension has much wider use, we can omit this section.

We added "legal context" for many of the extensions created for the OCDS for EU profile, because the legal context somewhat justifies the existence of the extension.

For common concepts like bids, our intention is not to catalogue the legal correspondence to every jurisdiction - so it seems a bit odd to give the EU extra consideration.

Note that sentence case (Legal context) should be used for headings.

```suggestion
```

2023-04-27 01:57 UTC, jpmckinney commented on extension.json
> +  ]
I think maybe we just copy the codelist in this extension. We copy `chargePaidBy.csv` for charges and tariffs, and `permission.csv` for contractTerms and submissionTerms.

2023-04-27 01:59 UTC, jpmckinney commented
Noting that `contracts.relatedBids` was discussed in https://github.com/open-contracting/european-union-support/issues/123. Using `awards.relatedBids` would become too convoluted in the eForms context.

2023-04-27 03:40 UTC, duncandewhurst commented on release-schema.json
> +          "description": "Whether this bid is ranked. For more information, see `.rank`.",
I think the relationship between `hasRank` and `rank` is clear enough that we can keep it short.

2023-04-27 03:46 UTC, duncandewhurst commented on extension.json
> +  ]
Done in https://github.com/open-contracting-extensions/ocds_bid_extension/pull/49/commits/b42d18f283407d470c60accdf0096de0fde50a63

2023-04-27 16:16 UTC, jpmckinney approved these changes

2023-04-27 16:16 UTC, merged